
name: Build and Publish Image

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LOCAL_IMAGE: 'local-image:latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: |
          docker build --no-cache --tag "${LOCAL_IMAGE}" --file 'Dockerfile' .
      
      - name: Test
        env:
          FOLDER_TEST: 'Test/'
        run: |
          if [ -d "${FOLDER_TEST}" ]
          then
            echo "${FOLDER_TEST}"
            ls ${FOLDER_TEST%/}/*.sh
          fi
      
      - name: Publish
        env:
          NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
          PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          BRANCH="${GITHUB_REF##*/}"
          REPOSITORY_NAME="${BRANCH}"
          TAG_NAME='latest'
          IMAGE_NAME="${NAMESPACE}/${REPOSITORY_NAME}:${TAG_NAME}"
          docker tag "${LOCAL_IMAGE}" ${IMAGE_NAME}
          USERNAME="${NAMESPACE##*/}"
          echo "${PASSWORD}" | docker login --username "${USERNAME}" --password-stdin
          docker push "${IMAGE_NAME}"
      
      - name: Clean
        run: |
          docker image rm "${LOCAL_IMAGE}"
