name: Build Docker Image

on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile

jobs:
  Test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test
        env:
          repository: "aws-tools"
          tag: "latest"
        run: |
          echo test
          ls
