name: Build Docker Image

on:
  push:
    branches:
      - aws-tools
    paths:
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Text
        env:
          repository: "aws-tools"
          tag: "latest"
        run: |
          echo test
          ls
