name: Distribute Github Workflows to Other Branches

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yaml
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Main to Other Branches
        run: |
          git branch --format='%(refname:short)' --no-column --all
          git config user.name
          git config user.email
          git config user.name 'Github Action Runner'
          git config user.name

      - name: Test
        run: |
          git branch --format='%(refname:short)' --no-column --all |
          while read -r branch
          do
            if [ "${branch}" != "main" ]
            then
              echo git checkout "${branch}"
              git checkout "${branch}"
              git merge main --no-edit
              git push origin "${branch}"
            fi
          done
